name: An unzip action workflow
on: push
jobs:
  build:
    name: Unzip action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        #with:
          #MY_NAME: "Brittany"
