name: An unzip action workflow
on: 
  push:
    branches:
      - '*'
jobs:
  build:
    name: Unzip action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Unzip
      run: |
        apt-get install unzip
    - name: Unzip file
      run: |
        unzip _latest.zip
      #- uses: ./action-a
        #with:
          #MY_NAME: "Brittany"
