name: An unzip action workflow
on: 
  push:
    branches:
      - '*'
jobs:
  build:
    name: Unzip action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Unzip
      run: |
        sudo apt-get install unzip
    - name: Unzip file
      run: |
        unzip _latest.zip
    - name: Commit zip contents
      run: |
        git config --global user.email "rebecca.watson@jedox.com"
        git config --global user.name "rebeccaawatson"
        git add *
        git commit -m "commit message here"
        git push
      #- uses: ./action-a
        #with:
          #MY_NAME: "Brittany"
