name: An unzip action workflow
on: 
  push:
    branches:
      - '*'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: Unzip action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Unzip
      run: |
        sudo apt-get install unzip
    - name: Unzip file
      run: |
        unzip -o _latest.zip
    - name: Commit unzipped contents
      run: |
        git config --local user.email "$(git log --format='%ae' HEAD^!)"
        git config --local user.name "$(git log --format='%an' HEAD^!)"
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only

        git add *

        git commit -m "Update Wizard model"
        git push github HEAD:${GITHUB_REF}
