on:
  pull_request:
    types: [opened]
    branches:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Zip action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Zip
      run: |
        sudo apt-get install zip
    - name: zip file
      run: |
        zip _latestNew WhatsNew.txt
    - name: Commit zipped contents
    - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}  
    
      run: |
         git config --local user.email "$(git log --format='%ae' HEAD^!)"
         git config --local user.name "$(git log --format='%an' HEAD^!)"
         git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
         git commit --allow-empty -m "New zipped Wizard model commited"
         git push origin HEAD:${{ github.head_ref }}
